apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        # Otel-Collector and Zipkin are ran on separate pods to allow for different scaling options
        - name: chromadb
          image: chromadb/chroma:1.0.21.dev43
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: chromadb-storage
              mountPath: /chroma/chroma
          env:
            - name: IS_PERSISTENT
              value: "TRUE"
            - name: PERSISTENT_DIRECTORY
              value: "/chroma/chroma"
            - name: ANONYMIZED_TELEMETRY
              value: "TRUE"
            - name: CHROMA_OPEN_TELEMETRY__ENDPOINT
              value: "http://otel-collector:4317"
            - name: CHROMA_OPEN_TELEMETRY__SERVICE_NAME
              value: chroma
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: chromadb-pv-claim
