apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: chromadb/chroma:1.0.21.dev43
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
