[workspace]
members = [
    "services/search-api",
    "services/embedding-service",
    "services/chromadb",
    "services/log-collector",
]

[workspace.dependencies]
anyhow = "1.0.99"
serde = "1.0.219"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
notify = { version = "8.1.0", features = ["serde"] }
