# Do not change this file, PersistentVolume configurations are handled by cluster admins.
# Create PersistentVolumeClaims to use admin created PresistentVolume
#
# NOTE: This configuration is only intended for local development and to be built upon, FAFO why
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
